### ISSUE TITLE
scss nesting

### ISSUE THREAD

**Issue by leggsimon** [leggsimon/code-audit#12]
Suggest changing nested modifiers eg:

```scss
.block__element {
    color: green;

    &--modifier {
        color: red;
    }

    &:hover {
        color: blue;
    }
}
```

To be separate selectors (excluding pseudo selectors) eg:
```scss
.block__element {
    color: green;

    &:hover {
        color: blue;
    }
}

.block__element--modifier {
    color: red;
}
```
